#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[198] =
    {   0,
        0,    0,   69,   67,   66,   66,   67,   33,   67,   31,
        2,    2,    2,    2,   30,   32,   65,   65,   65,   59,
       65,   56,   60,   57,   58,   65,   65,   65,    0,    3,
        0,    0,    0,   35,    0,    0,    0,   52,   48,    0,
        0,   36,    0,    2,    2,    0,    2,    0,   65,   65,
       65,   53,   65,   65,   24,   65,   65,   65,   54,   65,
       65,   65,   65,   65,   25,   65,   65,   65,   65,   55,
        0,    0,    0,    0,   43,    0,   42,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    1,   63,
        1,    2,   64,   65,   20,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       21,   23,   65,   65,   65,   65,   41,    0,    0,    0,
        0,   46,    0,    0,   45,    0,    0,   47,   44,    0,
        0,    5,   65,   65,   22,   61,   65,   65,   26,   62,
       65,   65,   65,   65,   12,   65,   65,   65,   65,   65,
       65,   65,   65,   49,    0,   51,    0,   40,   37,   34,
       38,    0,    0,    0,    0,   28,   27,    9,    4,   13,
       65,   65,   65,   15,   17,   10,   29,   65,   16,   18,
       65,    0,   50,    6,    0,   14,    7,   19,    8,   65,
       39,    6,    6,    6,   11,    6,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    7,    8,    9,    9,   10,
       11,    9,   12,    9,    9,   13,   13,    1,    1,    1,
       14,    1,   15,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       25,   32,   33,   34,   35,   36,   37,   25,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   25,   50,   51,   52,   53,
       54,   55,   25,   56,   57,   58,   59,   60,   61,   25,
       62,   63,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    4,    4,
        4,    4,    4,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    6,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5
    } ;

static const flex_int16_t yy_base[211] =
    {   0,
        0,    0,  185, 1485, 1485, 1485,   61, 1485,   50,    0,
       77,  101,  106,  119, 1485, 1485,  124,  129,  167,  144,
      207,  151,  170,  251,  179,  296,  216,  242,   72, 1485,
       48,   47,   50,  148,   46,   54,   84,  107, 1485,   96,
       42,  213,  320,  149,  343,  113,  352,  116,  357,  213,
      362,  262,  360,  356,  183,  363,  394,  407,  399,  442,
      447,  416,  492,  299,  449,  493,  528,  527,  533,  540,
      107,  136,  371,  189, 1485,  186, 1485,  224,  238,  147,
      241,  253,  259,  259,    0,  478,  593,  599,  586, 1485,
      604,  609, 1485,  614,  602,  605,  610,  642,  643,  654,

      679,  687,  692,  708,  724,  761,  739,  746,  772,  783,
      794,  805,  821,  826,  857,  838, 1485,  264,  151,  268,
      167, 1485,  230,  277, 1485,  294,  339, 1485, 1485,  892,
      910,  915,  489,  913,  626,  914,  913,  947,  965,  970,
      979,  985,  990, 1002, 1024, 1008, 1027, 1038, 1050, 1061,
     1081, 1083, 1109, 1485,  289, 1485,  328, 1485, 1485, 1485,
     1485,    0, 1162, 1169, 1176, 1104, 1110, 1174, 1183, 1183,
     1187,  991, 1207, 1200, 1223, 1232, 1239, 1240, 1248, 1255,
     1277,  360, 1485, 1307, 1331, 1296, 1298, 1299, 1325, 1334,
     1485, 1386, 1391, 1396, 1384, 1406, 1485, 1446,  138, 1449,

     1453, 1456,  119, 1460, 1463, 1467,  116, 1472, 1475, 1478
    } ;

static const flex_int16_t yy_def[211] =
    {   0,
      197,    1,  197,  197,  197,  197,  198,  197,  197,  199,
      197,  197,  197,  197,  197,  197,  200,  200,  200,  200,
       19,   19,   19,   19,   19,   19,   19,   19,  198,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  201,  197,  197,  197,  197,  197,  202,   19,
      202,   19,   19,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   21,   63,   24,   24,   24,   63,   24,   24,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  203,  204,  201,  204,  197,  197,
      205,  205,  197,  202,   24,   24,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  206,
      204,  205,   19,   19,   19,   19,   24,  200,  200,  200,
      200,  200,  200,  200,  200,   19,   19,   19,   19,   19,
       19,   19,   19,  197,  197,  197,  197,  197,  197,  197,
      197,  207,  208,  206,  208,   19,   19,   19,  202,   19,
       19,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,  197,  197,  209,  208,   24,   24,   24,   24,   24,
      197,  210,  209,  210,   24,  210,    0,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197
    } ;

static const flex_int16_t yy_nxt[1549] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
       13,   11,   14,   15,   16,   17,   18,   19,   17,   20,
       21,   17,   17,   17,   17,   22,   23,   24,   17,   17,
       25,   26,   17,   17,   27,   17,   28,   17,   17,    4,
       17,   18,   19,   17,   20,   21,   17,   17,   17,   22,
       23,   24,   17,   17,   25,   26,   17,   17,   27,   17,
       28,   17,   17,   30,   30,   31,   71,   32,   33,   73,
       34,   35,   77,   36,   30,   30,   72,   76,   37,   82,
       38,   39,   40,   41,   42,   44,   44,   44,   44,   45,
       31,   71,   32,   33,   73,   34,   35,   77,   36,   78,

       72,   76,   37,   82,   38,   39,   40,   41,   42,   44,
       44,   44,   44,   45,   44,   44,   44,   47,   45,   81,
      184,   46,   79,  130,   78,  117,   48,   45,   45,   45,
       45,   45,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   43,   80,   81,   90,   46,   79,   93,   52,
      117,   48,   49,   49,   49,   49,   49,   89,   89,   89,
       89,   45,   56,   51,  118,  125,   50,   80,   51,   90,
      155,   74,   93,   50,   52,   49,   49,   49,   49,   49,
       75,   50,   53,   51,  197,   50,  157,   56,  118,   54,
      125,   50,   50,  197,   66,  155,   74,   55,   50,   62,

       50,   50,  197,  197,   75,   50,   51,   53,   50,   50,
       50,  157,   50,  197,   54,  121,  122,   50,   50,   66,
      197,   55,   57,   62,   50,   58,   50,   59,   50,   50,
       60,   50,   50,   50,   83,   50,   50,   50,   50,  121,
      122,   61,   50,   50,   69,   84,   50,   57,  197,  158,
       58,  123,   59,   50,   50,   60,   50,   50,  197,   83,
       50,   50,   70,   50,   50,   61,   50,   50,   69,   84,
       50,  124,   50,   50,  158,  123,   63,   50,  197,  126,
       64,   50,   50,  127,   50,  197,   65,   70,  128,   50,
      129,   50,   50,  197,  197,  124,   50,  154,   50,  159,

       63,  156,   50,  126,   64,   50,  197,  127,  197,   50,
       65,   50,  128,  160,  129,   67,   50,   50,   50,   50,
       50,  154,  182,   68,  159,  156,   50,   85,   86,   86,
       86,   86,   86,  109,  197,  197,   50,  197,  160,  197,
       67,  197,   50,   50,   50,   50,  182,   68,  197,  197,
       50,   45,   45,   45,   45,   45,  183,  109,  161,   88,
       91,   91,   91,   91,   92,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   50,  197,   96,  197,  191,
      183,   50,   50,  161,  197,   97,   98,  197,   50,  197,
       50,   50,   50,   95,  197,  197,   51,  119,   50,  197,

       50,   51,   96,  120,  191,   50,  197,   50,  197,   97,
      197,   98,   50,  197,   50,   50,   50,   95,  197,   50,
      197,  119,   50,   50,   50,  197,   99,  120,   50,   50,
      100,  197,   50,  197,   50,  197,   50,  104,  197,  197,
      197,   50,   50,   50,  197,   50,  197,   50,   50,  197,
       99,   50,   50,   50,  197,  100,   50,  197,   50,  197,
       50,  197,  104,  197,  197,   50,   50,   50,  101,   50,
      102,   50,   50,  103,   50,   50,   50,   50,   50,  197,
      197,  197,   50,  197,   50,   85,   86,   86,   86,   86,
       86,   50,  101,  197,  102,   50,   50,  103,   50,  197,

       50,   50,   50,  197,   50,  197,   50,   50,   50,  197,
      105,   50,  106,  107,  197,   50,  197,   88,   50,  166,
      197,  197,   50,  197,  197,  197,  108,  110,   50,   50,
      197,  197,   50,  197,  197,  105,   50,  106,  107,  197,
       50,  197,   50,  166,  197,  113,   50,   50,  114,  197,
      108,  110,   50,   50,  197,  111,  112,   50,   50,  197,
      116,  115,   50,   50,  197,   50,  197,  197,   50,   50,
      113,  197,   50,  114,  197,   50,  197,   50,  197,  111,
      112,   50,   50,  197,  116,  115,   50,   50,  197,   50,
      197,  197,   50,   50,   45,   45,   45,   45,   45,   50,

       85,   86,   86,   86,   86,   86,   85,   86,   86,   86,
       86,   86,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   49,   49,   49,   49,   49,   50,  197,  197,
       50,   50,   88,  197,   50,   50,  133,   50,   88,   50,
       50,   50,  197,  197,  197,   50,  134,  197,   50,  197,
      197,   50,  197,   51,   50,   50,   50,  197,   50,   50,
      133,   50,  197,   50,   50,  197,   50,   50,   50,   50,
      134,   50,   50,   50,  197,  135,  136,   50,   50,   50,
       50,  197,  197,   50,  197,  197,  137,  197,  197,   50,
      197,   50,   50,  197,  197,   50,   50,  197,  138,  135,

      136,   50,   50,   50,   50,  139,  197,   50,   50,  197,
      137,  197,   50,   50,   50,  197,   50,   50,  140,  197,
      197,   50,   50,  138,  197,  197,  197,   50,   50,  197,
      139,  141,   50,   50,  197,  197,   50,  142,   50,  197,
       50,   50,  140,   50,  197,   50,   50,  143,  197,   50,
      197,   50,  197,   50,  197,  197,  141,   50,  197,   50,
      197,  142,  197,  197,   50,  197,  197,   50,   50,  197,
      146,   50,  143,   50,   50,   50,  197,   50,  147,  197,
      197,   50,  197,   50,  144,  197,   50,  197,   50,  197,
       50,  197,   50,  145,  146,   50,   50,   50,   50,   50,

      148,   50,  147,  197,  197,   50,  197,   50,   50,  144,
       50,  197,   50,  197,   50,  149,  197,  145,   50,   50,
       50,   50,  197,   50,  148,   50,  197,  197,  197,   50,
       50,   50,   50,  197,   50,  197,   50,  197,  197,  149,
       50,  197,   50,   50,  150,  197,   50,   50,  197,  197,
       50,   50,  197,   50,   50,   50,   50,  151,   50,  197,
      197,   50,  197,   50,   50,  197,  197,  153,  197,  150,
       50,  197,  197,   50,   50,   50,  197,  197,  197,   50,
       50,  151,   50,  197,  197,   50,   50,   50,  197,  152,
      197,  153,   50,  197,  197,  197,  197,   50,  162,   85,

      163,  163,  163,  163,  163,  197,   50,  197,  197,  197,
       50,  197,  197,  152,  197,  197,   50,   85,   86,   86,
       86,   86,   86,  197,  197,  197,  197,  197,   50,   50,
      197,  165,  197,  197,  197,   50,   50,  197,  168,  197,
      197,  167,   50,   50,   50,  197,  197,  197,   50,   88,
      197,  197,  197,   50,   50,  169,  169,  169,  169,  169,
       50,   50,  168,  197,  197,  167,   50,   50,   50,  197,
      197,  197,   50,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,  197,  197,  197,   51,   49,   49,   49,
       49,   49,  197,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,  197,   51,  197,  197,  170,  197,   51,
       49,   49,   49,   49,   49,  197,  187,  197,   51,  171,
       50,  197,  172,   50,   51,  197,   50,  197,  173,   51,
       50,  170,   49,   49,   49,   49,   49,  197,  174,  197,
      187,   51,   50,  171,   50,  197,  172,  197,   50,   50,
       50,  197,  173,   50,  197,   50,  197,   50,  175,  197,
       50,  197,  174,   51,  197,   50,  197,   50,   50,  177,
      197,  176,   50,  197,   50,  197,   50,  197,   50,  197,
       50,   50,  175,   50,  197,   50,  197,  197,  197,  197,
       50,   50,   50,  178,  177,  176,   50,   50,   50,  197,

      197,   50,  197,   50,   50,   50,  197,  197,   50,  197,
      197,  179,  197,   50,  180,   50,  197,  178,  197,   50,
      197,   50,  197,   50,   50,   50,   50,  197,   50,  197,
       50,   50,   50,  197,   50,  179,  197,   50,  180,   50,
       50,  197,  197,  181,   50,  197,  197,  197,  197,   50,
       50,   50,  197,  197,  197,  197,   50,   50,   50,  197,
      197,  197,  197,   50,   50,  197,  197,  181,  162,   85,
      163,  163,  163,  163,  163,  162,   85,  163,  163,  163,
      163,  163,  162,   85,  163,  163,  163,  163,  163,   50,
      197,  169,  169,  169,  169,  169,   50,  197,   50,  197,

      197,  165,   50,  197,   50,   50,  197,  197,  165,   50,
      197,  197,  197,   50,   50,  165,  197,   50,  197,  197,
      186,   50,   51,   50,  197,   50,  188,   50,   50,   50,
       50,  197,   50,  197,   50,   50,   50,   50,  197,  197,
      197,   50,   50,  197,  186,  197,  197,  197,   50,   50,
      197,  188,   50,   50,  197,  197,   50,   50,   50,   50,
       50,   50,  197,  197,   50,  189,   50,   50,   50,   50,
      197,  197,   50,   50,   50,   50,   50,   50,  197,  197,
       50,   50,   50,   50,   50,   50,  197,  197,   50,  189,
       50,   50,   50,   50,  197,  197,  197,   50,   50,   50,

      197,   50,   50,  197,   50,  190,   50,   50,   50,  197,
      197,  197,   50,  197,   50,  192,  192,  192,  192,  192,
      197,   50,  197,   50,   50,   50,   50,   50,   50,  190,
       50,   50,  197,   50,   50,  197,   50,  162,   85,  163,
      163,  163,  163,  163,  197,   50,  194,   50,   50,   50,
       50,   50,   50,  197,   50,   50,  197,   50,   50,   50,
       50,  197,  197,   50,  197,  197,  197,  195,  197,   50,
      165,  197,  197,  197,   50,  197,  197,  197,   50,  197,
      197,  197,  197,   50,   50,  197,  197,   50,  197,  197,
      197,  195,  197,   50,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,   50,
      197,  197,  197,   50,  192,  192,  192,  192,  192,   50,
      197,  197,  197,  197,  197,  194,  197,  197,  197,  197,
      194,  197,  197,   50,  197,  194,  197,   50,  197,  197,
      197,  197,  197,   50,  197,  194,   29,   29,   29,   29,
       29,   29,   50,   50,   50,   87,   87,   87,   87,   94,
       94,   94,  131,  131,  131,  131,  132,  132,  164,  164,
      164,  164,  164,  185,  185,  185,  185,  185,  193,  193,
      193,  196,  196,  196,    3,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

static const flex_int16_t yy_chk[1549] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    7,    9,   31,    9,    9,   33,
        9,    9,   36,    9,   29,   29,   32,   35,    9,   41,
        9,    9,    9,    9,    9,   11,   11,   11,   11,   11,
        9,   31,    9,    9,   33,    9,    9,   36,    9,   37,

       32,   35,    9,   41,    9,    9,    9,    9,    9,   12,
       12,   12,   12,   12,   13,   13,   13,   13,   13,   40,
      207,   12,   38,  203,   37,   71,   13,   14,   14,   14,
       14,   14,   17,   17,   17,   17,   17,   18,   18,   18,
       18,   18,  199,   38,   40,   46,   12,   38,   48,   18,
       71,   13,   20,   20,   20,   20,   20,   44,   44,   44,
       44,   44,   20,   17,   72,   80,   22,   38,   18,   46,
      119,   34,   48,   22,   18,   19,   19,   19,   19,   19,
       34,   22,   19,   20,    3,   23,  121,   20,   72,   19,
       80,   22,   23,    0,   25,  119,   34,   19,   22,   23,

       23,   25,    0,    0,   34,   22,   19,   19,   55,   25,
       23,  121,   55,    0,   19,   74,   76,   23,   55,   25,
        0,   19,   21,   23,   23,   21,   25,   21,   50,   21,
       21,   27,   55,   25,   42,   50,   55,   21,   27,   74,
       76,   21,   55,   50,   27,   42,   27,   21,    0,  123,
       21,   78,   21,   50,   21,   21,   27,   28,    0,   42,
       50,   21,   28,   27,   28,   21,   24,   50,   27,   42,
       27,   79,   28,   24,  123,   78,   24,   52,    0,   81,
       24,   24,   28,   82,   52,    0,   24,   28,   83,   28,
       84,   24,   52,    0,    0,   79,   28,  118,   24,  124,

       24,  120,   52,   81,   24,   24,    0,   82,    0,   52,
       24,   26,   83,  126,   84,   26,   52,   64,   26,   64,
       64,  118,  155,   26,  124,  120,   26,   43,   43,   43,
       43,   43,   43,   64,    0,    0,   26,    0,  126,    0,
       26,    0,   64,   26,   64,   64,  155,   26,    0,    0,
       26,   45,   45,   45,   45,   45,  157,   64,  127,   43,
       47,   47,   47,   47,   47,   49,   49,   49,   49,   49,
       51,   51,   51,   51,   51,   53,    0,   54,    0,  182,
      157,   54,   53,  127,    0,   54,   56,    0,   56,    0,
       53,   54,   56,   53,    0,    0,   49,   73,   56,    0,

       53,   51,   54,   73,  182,   54,    0,   53,    0,   54,
        0,   56,   56,    0,   53,   54,   56,   53,    0,   57,
        0,   73,   56,   57,   59,    0,   57,   73,   59,   57,
       58,    0,   58,    0,   59,    0,   58,   62,    0,    0,
        0,   62,   58,   57,    0,   62,    0,   57,   59,    0,
       57,   62,   59,   57,    0,   58,   58,    0,   59,    0,
       58,    0,   62,    0,    0,   62,   58,   60,   60,   62,
       60,   60,   61,   61,   65,   62,   61,   60,   65,    0,
        0,    0,   61,    0,   65,   86,   86,   86,   86,   86,
       86,   60,   60,    0,   60,   60,   61,   61,   65,    0,

       61,   60,   65,    0,  133,    0,   61,   63,   65,    0,
       63,  133,   63,   63,    0,   63,    0,   86,   66,  133,
        0,    0,   66,    0,    0,    0,   63,   66,   66,  133,
        0,    0,   63,    0,    0,   63,  133,   63,   63,    0,
       63,    0,   66,  133,    0,   68,   66,   68,   68,    0,
       63,   66,   66,   67,    0,   67,   67,   67,   69,    0,
       69,   68,   69,   67,    0,   70,    0,    0,   69,   70,
       68,    0,   68,   68,    0,   70,    0,   67,    0,   67,
       67,   67,   69,    0,   69,   68,   69,   67,    0,   70,
        0,    0,   69,   70,   89,   89,   89,   89,   89,   70,

       87,   87,   87,   87,   87,   87,   88,   88,   88,   88,
       88,   88,   91,   91,   91,   91,   91,   92,   92,   92,
       92,   92,   94,   94,   94,   94,   94,   95,    0,    0,
       96,   95,   87,    0,   96,   97,   96,   95,   88,   97,
       96,  135,    0,    0,    0,   97,   97,    0,  135,    0,
        0,   95,    0,   94,   96,   95,  135,    0,   96,   97,
       96,   95,    0,   97,   96,    0,  135,   98,   99,   97,
       97,   98,   99,  135,    0,   98,   99,   98,   99,  100,
      135,    0,    0,  100,    0,    0,  100,    0,    0,  100,
        0,   98,   99,    0,    0,   98,   99,    0,  101,   98,

       99,   98,   99,  100,  101,  102,    0,  100,  101,    0,
      100,    0,  102,  100,  101,    0,  102,  103,  103,    0,
        0,  103,  102,  101,    0,    0,    0,  103,  101,    0,
      102,  104,  101,  104,    0,    0,  102,  104,  101,    0,
      102,  103,  103,  104,    0,  103,  102,  105,    0,  105,
        0,  103,    0,  105,    0,    0,  104,  104,    0,  105,
        0,  104,    0,    0,  107,    0,    0,  104,  107,    0,
      107,  108,  105,  105,  107,  108,    0,  105,  108,    0,
        0,  108,    0,  105,  106,    0,  106,    0,  107,    0,
      106,    0,  107,  106,  107,  108,  106,  109,  107,  108,

      109,  109,  108,    0,    0,  108,    0,  109,  110,  106,
      106,    0,  110,    0,  106,  110,    0,  106,  110,  111,
      106,  109,    0,  111,  109,  109,    0,    0,    0,  111,
      112,  109,  110,    0,  112,    0,  110,    0,    0,  110,
      112,    0,  110,  111,  113,    0,  113,  111,    0,    0,
      113,  114,    0,  111,  112,  114,  113,  114,  112,    0,
        0,  114,    0,  116,  112,    0,    0,  116,    0,  113,
      113,    0,    0,  116,  113,  114,    0,    0,    0,  114,
      113,  114,  115,    0,    0,  114,  115,  116,    0,  115,
        0,  116,  115,    0,    0,    0,    0,  116,  130,  130,

      130,  130,  130,  130,  130,    0,  115,    0,    0,    0,
      115,    0,    0,  115,    0,    0,  115,  131,  131,  131,
      131,  131,  131,  132,  132,  132,  132,  132,  134,  136,
        0,  130,    0,    0,    0,  134,  136,    0,  137,    0,
        0,  134,  137,  134,  136,    0,    0,    0,  137,  131,
        0,    0,    0,  134,  136,  138,  138,  138,  138,  138,
      134,  136,  137,    0,    0,  134,  137,  134,  136,    0,
        0,    0,  137,  139,  139,  139,  139,  139,  140,  140,
      140,  140,  140,    0,    0,    0,  138,  141,  141,  141,
      141,  141,    0,  142,  142,  142,  142,  142,  143,  143,

      143,  143,  143,    0,  139,    0,    0,  141,    0,  140,
      144,  144,  144,  144,  144,    0,  172,    0,  141,  142,
      172,    0,  143,  146,  142,    0,  172,    0,  144,  143,
      146,  141,  145,  145,  145,  145,  145,    0,  146,    0,
      172,  144,  147,  142,  172,    0,  143,    0,  146,  147,
      172,    0,  144,  148,    0,  146,    0,  147,  147,    0,
      148,    0,  146,  145,    0,  149,    0,  147,  148,  149,
        0,  148,  149,    0,  147,    0,  150,    0,  148,    0,
      149,  147,  147,  150,    0,  148,    0,    0,    0,    0,
      149,  150,  148,  150,  149,  148,  151,  149,  152,    0,

        0,  150,    0,  151,  149,  152,    0,    0,  150,    0,
        0,  151,    0,  152,  152,  150,    0,  150,    0,  166,
        0,  151,    0,  152,  153,  167,  166,    0,  151,    0,
      152,  153,  167,    0,  166,  151,    0,  152,  152,  153,
      167,    0,    0,  153,  166,    0,    0,    0,    0,  153,
      167,  166,    0,    0,    0,    0,  153,  167,  166,    0,
        0,    0,    0,  153,  167,    0,    0,  153,  163,  163,
      163,  163,  163,  163,  163,  164,  164,  164,  164,  164,
      164,  164,  165,  165,  165,  165,  165,  165,  165,  168,
        0,  169,  169,  169,  169,  169,  168,    0,  170,    0,

        0,  163,  171,    0,  168,  170,    0,    0,  164,  171,
        0,    0,    0,  170,  168,  165,    0,  171,    0,    0,
      171,  168,  169,  170,    0,  174,  173,  171,  168,  174,
      170,    0,  173,    0,  171,  174,  173,  170,    0,    0,
        0,  171,  173,    0,  171,    0,    0,    0,  175,  174,
        0,  173,  175,  174,    0,    0,  173,  176,  175,  174,
      173,  176,    0,    0,  177,  178,  173,  176,  177,  178,
        0,    0,  175,  179,  177,  178,  175,  179,    0,    0,
      180,  176,  175,  179,  180,  176,    0,    0,  177,  178,
      180,  176,  177,  178,    0,    0,    0,  179,  177,  178,

        0,  179,  181,    0,  180,  181,  181,  179,  180,    0,
        0,    0,  181,    0,  180,  184,  184,  184,  184,  184,
        0,  186,    0,  187,  188,  186,  181,  187,  188,  181,
      181,  186,    0,  187,  188,    0,  181,  185,  185,  185,
      185,  185,  185,  185,    0,  186,  184,  187,  188,  186,
      189,  187,  188,    0,  189,  186,    0,  187,  188,  190,
      189,    0,    0,  190,    0,    0,    0,  190,    0,  190,
      185,    0,    0,    0,  189,    0,    0,    0,  189,    0,
        0,    0,    0,  190,  189,    0,    0,  190,    0,    0,
        0,  190,    0,  190,  192,  192,  192,  192,  192,  193,

      193,  193,  193,  193,  194,  194,  194,  194,  194,  195,
        0,    0,    0,  195,  196,  196,  196,  196,  196,  195,
        0,    0,    0,    0,    0,  192,    0,    0,    0,    0,
      193,    0,    0,  195,    0,  194,    0,  195,    0,    0,
        0,    0,    0,  195,    0,  196,  198,  198,  198,  198,
      198,  198,  200,  200,  200,  201,  201,  201,  201,  202,
      202,  202,  204,  204,  204,  204,  205,  205,  206,  206,
      206,  206,  206,  208,  208,  208,  208,  208,  209,  209,
      209,  210,  210,  210,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 2 "lexico.l"
    #include <iostream>
    #include "parser.h"
    int resultado;
#line 858 "scanner.cpp"
#line 859 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 21 "lexico.l"


#line 1079 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 198 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1485 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "lexico.l"
{yylval.TEXT = yytext; return(ugo);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "lexico.l"
{yylval.TEXT = yytext; return(digito);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 25 "lexico.l"
{yylval.TEXT = yytext; return(cadena);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "lexico.l"
{yylval.TEXT = yytext; return(filen);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "lexico.l"
{yylval.TEXT = yytext; return(idp);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "lexico.l"
{yylval.TEXT = yytext; return(ruta);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 "lexico.l"
{yylval.TEXT = yytext; return(mkdisk);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "lexico.l"
{yylval.TEXT = yytext; return(rmdisk);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "lexico.l"
{yylval.TEXT = yytext; return(fdisk);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 "lexico.l"
{yylval.TEXT = yytext; return(mount);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 "lexico.l"
{yylval.TEXT = yytext; return(unmount);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "lexico.l"
{yylval.TEXT = yytext; return(mkfs);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "lexico.l"
{yylval.TEXT = yytext; return(login);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "lexico.l"
{yylval.TEXT = yytext; return(logout);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "lexico.l"
{yylval.TEXT = yytext; return(mkgrp);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "lexico.l"
{yylval.TEXT = yytext; return(rmgrp);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "lexico.l"
{yylval.TEXT = yytext; return(mkusr);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "lexico.l"
{yylval.TEXT = yytext; return(rmusr);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "lexico.l"
{yylval.TEXT = yytext; return(mkfile);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "lexico.l"
{yylval.TEXT = yytext; return(cat);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "lexico.l"
{yylval.TEXT = yytext; return(rem);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "lexico.l"
{yylval.TEXT = yytext; return(edit);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "lexico.l"
{yylval.TEXT = yytext; return(ren);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "lexico.l"
{yylval.TEXT = yytext; return(cp);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "lexico.l"
{yylval.TEXT = yytext; return(mv);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "lexico.l"
{yylval.TEXT = yytext; return(find);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "lexico.l"
{yylval.TEXT = yytext; return(chownn);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "lexico.l"
{yylval.TEXT = yytext; return(chgrp);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "lexico.l"
{yylval.TEXT = yytext; return(pausee);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "lexico.l"
{yylval.TEXT = yytext; return(igual);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "lexico.l"
{yylval.TEXT = yytext; return(dividido);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "lexico.l"
{yylval.TEXT = yytext; return(interrogacion);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "lexico.l"
{yylval.TEXT = yytext; return(multiplicacion);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "lexico.l"
{yylval.TEXT = yytext; return(sizee);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "lexico.l"
{yylval.TEXT = yytext; return(f);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "lexico.l"
{yylval.TEXT = yytext; return(u);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "lexico.l"
{yylval.TEXT = yytext; return(pathh);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "lexico.l"
{yylval.TEXT = yytext; return(typee);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "lexico.l"
{yylval.TEXT = yytext; return(deletee);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "lexico.l"
{yylval.TEXT = yytext; return(namee);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "lexico.l"
{yylval.TEXT = yytext; return(addd);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "lexico.l"
{yylval.TEXT = yytext; return(id);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "lexico.l"
{yylval.TEXT = yytext; return(fs);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "lexico.l"
{yylval.TEXT = yytext; return(usr);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "lexico.l"
{yylval.TEXT = yytext; return(pwd);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "lexico.l"
{yylval.TEXT = yytext; return(grp);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "lexico.l"
{yylval.TEXT = yytext; return(ugoo);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "lexico.l"
{yylval.TEXT = yytext; return(r);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "lexico.l"
{yylval.TEXT = yytext; return(cont);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "lexico.l"
{yylval.TEXT = yytext; return(filenn);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "lexico.l"
{yylval.TEXT = yytext; return(dest);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "lexico.l"
{yylval.TEXT = yytext; return(p);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "lexico.l"
{yylval.TEXT = yytext; return(BF);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "lexico.l"
{yylval.TEXT = yytext; return(FF);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "lexico.l"
{yylval.TEXT = yytext; return(WF);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "lexico.l"
{yylval.TEXT = yytext; return(K);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "lexico.l"
{yylval.TEXT = yytext; return(M);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "lexico.l"
{yylval.TEXT = yytext; return(PP);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "lexico.l"
{yylval.TEXT = yytext; return(E);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "lexico.l"
{yylval.TEXT = yytext; return(L);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "lexico.l"
{yylval.TEXT = yytext; return(FAST);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "lexico.l"
{yylval.TEXT = yytext; return(FULL);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "lexico.l"
{yylval.TEXT = yytext; return(FS2);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "lexico.l"
{yylval.TEXT = yytext; return(FS3);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 94 "lexico.l"
{yylval.TEXT = yytext; return(ident);}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 95 "lexico.l"
{}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 97 "lexico.l"
{std::cout<<"Error Lexico"<<std::endl;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 98 "lexico.l"
ECHO;
	YY_BREAK
#line 1478 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 198 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 198 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 197);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 98 "lexico.l"


